// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvswf9ehMZrKWojI7iRC5Yl-XapDoCTTs',
    appId: '1:1052791010602:web:a18e520d7ef7f14efc9a53',
    messagingSenderId: '1052791010602',
    projectId: 'notes-1b051',
    authDomain: 'notes-1b051.firebaseapp.com',
    storageBucket: 'notes-1b051.firebasestorage.app',
    measurementId: 'G-NBGH70R7ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB70RpUQ4hHxTjyttrP9DbJQd_8lqaPl4g',
    appId: '1:1052791010602:android:f6a62e2b4aef3450fc9a53',
    messagingSenderId: '1052791010602',
    projectId: 'notes-1b051',
    storageBucket: 'notes-1b051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb-F1Sbc5TnTik323Unnk-ud2xucnetjU',
    appId: '1:1052791010602:ios:c7ca93748ba281f7fc9a53',
    messagingSenderId: '1052791010602',
    projectId: 'notes-1b051',
    storageBucket: 'notes-1b051.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb-F1Sbc5TnTik323Unnk-ud2xucnetjU',
    appId: '1:1052791010602:ios:c7ca93748ba281f7fc9a53',
    messagingSenderId: '1052791010602',
    projectId: 'notes-1b051',
    storageBucket: 'notes-1b051.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvswf9ehMZrKWojI7iRC5Yl-XapDoCTTs',
    appId: '1:1052791010602:web:70aac5a098815f10fc9a53',
    messagingSenderId: '1052791010602',
    projectId: 'notes-1b051',
    authDomain: 'notes-1b051.firebaseapp.com',
    storageBucket: 'notes-1b051.firebasestorage.app',
    measurementId: 'G-8L1Z5DE2QC',
  );

}